
import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
// import { Inter } from 'next/font/google'
import { Ovo, Roboto } from 'next/font/google'
import { ShopContextProvider } from './context/ShopContext'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const ovo = Ovo({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-ovo",
  display: "swap"
})

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
  display: "swap"
})


// const ovo = Ovo({ weight: "400", subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const metadata = {
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
  // PermissionsPolicy: {
  //   interestCohort: "()"
  // }
}

// trying to fix error in console with below code, no success thus far
{/* <meta http-equiv="Permissions-Policy" content="interest-cohort=()"> */}

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{scrollBehavior: "smooth"}} className={`${ovo.variable} ${roboto.variable} text-gray-600`}>
      <ShopContextProvider>
        <body>
          <Header />
          {children}
          <Footer />
          <ToastContainer
            position="top-center"
            autoClose={2000}
            hideProgressBar={true}
          />
        </body>
      </ShopContextProvider>
    </html>
  )
}
